
name: Continuous Integration

on:
  push:
    tags:
      - "v*.*.*"

env:
  RELEASE_VERSION: ${GITHUB_REF#refs/*/}

jobs:
  release:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/actions/checkout/issues/1169
      - name: Workaround Git Security Warning
        run: |
          # Workaround a bug in github actions:
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dogechainlab/graph-node
          tags: |
            type=ref,event=tag
            type=sha,format=long

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            COMMIT_SHA=${GITHUB_SHA}
            REPO_NAME=${GITHUB_REPOSITORY}
            BRANCH_NAME=${env.GITHUB_REF_NAME}
            TAG_NAME=${env.RELEASE_VERSION}
